/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Guest;

import View_.*;
import Entity_.Payment;
import Entity_.Student;
import Service_.PaymentService;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import Service_.RegisterService;

/**
 *
 * @author MY_PC
 */
public class coursePaymentDetailsForm_Guest extends javax.swing.JFrame {

    /**
     * Creates new form addNewCoursePaymentForm
     */
    Payment p;
    private PaymentService ps = new PaymentService();

    private RegisterService rs = new RegisterService();

    public coursePaymentDetailsForm_Guest() {
        initComponents();
        this.setLocationRelativeTo(null);
        a.setBackground(new Color(250, 250, 250));
        b.setBackground(new Color(250, 250, 250));
        c.setBackground(new Color(250, 250, 250));
        d.setBackground(new Color(250, 250, 250));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        studentName = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        paymentPlan = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        courseFee = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursePaymentTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        d = new javax.swing.JPanel();
        a = new javax.swing.JPanel();
        b = new javax.swing.JPanel();
        c = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        studentId = new javax.swing.JLabel();
        idLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 55));
        jLabel25.setText("Student Name");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, 30));

        studentName.setBackground(new java.awt.Color(204, 204, 204));
        studentName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        studentName.setOpaque(true);
        jPanel2.add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 260, 20));

        course.setBackground(new java.awt.Color(204, 204, 204));
        course.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        course.setOpaque(true);
        jPanel2.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 260, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 55));
        jLabel24.setText("Course");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 80, 30));

        paymentPlan.setBackground(new java.awt.Color(204, 204, 204));
        paymentPlan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        paymentPlan.setOpaque(true);
        jPanel2.add(paymentPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 260, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 55));
        jLabel26.setText("Payment Plan");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 55));
        jLabel28.setText("Course Fee");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 110, 30));

        courseFee.setBackground(new java.awt.Color(204, 204, 204));
        courseFee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        courseFee.setOpaque(true);
        jPanel2.add(courseFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 260, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 55));
        jLabel3.setText("Rs:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, -1));

        coursePaymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(coursePaymentTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 670, 300));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel15.setToolTipText(" Back");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 50, 40));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 55));
        jLabel29.setText("Registation Fee");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 110, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 55));
        jLabel31.setText("Library Fee");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 110, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 55));
        jLabel30.setText("Development Fee");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 120, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 55));
        jLabel33.setText("Other Fee");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 80, 30));
        jPanel2.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 20, 20));
        jPanel2.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 20, 20));
        jPanel2.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 20, 20));
        jPanel2.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 20, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1120, 460));

        jPanel1.setBackground(new java.awt.Color(51, 52, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("X");
        jLabel32.setToolTipText("close");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 30, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-");
        jLabel22.setToolTipText("minimize");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 30, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 230, 230));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_card_payment_88px.png"))); // NOI18N
        jLabel6.setText("NSBM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setText("Student.Pay.Mgt System");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 230, 230));
        jLabel8.setText("Stu.Course.Payment.Details");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 620, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_30px.png"))); // NOI18N
        jLabel1.setToolTipText("Search");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, 40));

        search.setBackground(new java.awt.Color(51, 52, 54));
        search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(240, 240, 240));
        search.setBorder(null);
        search.setOpaque(false);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 280, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 280, 20));

        studentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studentId.setForeground(new java.awt.Color(240, 240, 240));
        studentId.setText("Student ID");
        jPanel1.add(studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        idLable.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(idLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 180, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(coursePaymentDetailsForm_Guest.ICONIFIED);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        StudentMain_Guest studentPaymentForm = new StudentMain_Guest();
        studentPaymentForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * search student,course,register details and payment details
     *
     * @param evt
     */
    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        p = new Payment();

        if (!search.getText().equals("")) {

            if (rs.checkStudentRegistrationPayment(search.getText())) {

                idLable.setText("");

                try {

                    //search student,course,register details
                    Student s = ps.search(search.getText());

                    studentName.setText(s.getsName());
                    paymentPlan.setText(s.getRegister().getPaymentPlan());
                    course.setText(s.getCourse().getaCourseName());
                    courseFee.setText(String.valueOf(s.getRegister().getCourseFee()));
                    a.setBackground(Color.green);
                    b.setBackground(Color.green);
                    c.setBackground(Color.green);
                    d.setBackground(Color.green);

                    //search payment details    
                    List<Payment> payments = ps.getAll(search.getText());

                    coursePaymentTable.setVisible(true);
                    String[] colName = {"Instalment", "Paid Amount", "Balance", "Date"};
                    Object[][] rows = new Object[payments.size()][48];

                    for (int i = 0; i < payments.size(); i++) {
                        rows[i][0] = payments.get(i).getInstalment();
                        rows[i][1] = payments.get(i).getPaidAmount();
                        rows[i][2] = payments.get(i).getBalance();
                        rows[i][3] = payments.get(i).getDate();
                    }
                    myModel mmd = new myModel(rows, colName);

                    coursePaymentTable.setModel(mmd);
                    coursePaymentTable.setRowHeight(70);
                    coursePaymentTable.setShowGrid(true);
                    coursePaymentTable.setGridColor(Color.black);
                    coursePaymentTable.setSelectionBackground(Color.lightGray);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else {
                idLable.setText("Not a Registed Student ID");
                clear();
            }

        } else {
            search.setText("");
            idLable.setText("");
            clear();
        }
    }//GEN-LAST:event_searchKeyReleased

    public class myModel extends AbstractTableModel {

        private String[] colums;
        private Object[][] rows;

        public myModel() {
        }

        public myModel(Object[][] data, String[] columnsName) {
            this.colums = columnsName;
            this.rows = data;
        }

        @Override
        public int getRowCount() {
            return this.rows.length;
        }

        @Override
        public int getColumnCount() {
            return this.colums.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            return this.rows[rowIndex][columnIndex];
        }

        @Override
        public String getColumnName(int col) {
            return this.colums[col];
        }

    }

    /**
     * clear fields
     */
    public void clear() {

        studentName.setText("");
        course.setText("");
        paymentPlan.setText("");
        courseFee.setText("");
        a.setBackground(new Color(250, 250, 250));
        b.setBackground(new Color(250, 250, 250));
        c.setBackground(new Color(250, 250, 250));
        d.setBackground(new Color(250, 250, 250));
        coursePaymentTable.setVisible(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coursePaymentDetailsForm_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coursePaymentDetailsForm_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coursePaymentDetailsForm_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coursePaymentDetailsForm_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coursePaymentDetailsForm_Guest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a;
    private javax.swing.JPanel b;
    private javax.swing.JPanel c;
    private javax.swing.JLabel course;
    private javax.swing.JLabel courseFee;
    private javax.swing.JTable coursePaymentTable;
    private javax.swing.JPanel d;
    private javax.swing.JLabel idLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel paymentPlan;
    private javax.swing.JTextField search;
    private javax.swing.JLabel studentId;
    private javax.swing.JLabel studentName;
    // End of variables declaration//GEN-END:variables
}
