/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_;

import Entity_.Course;
import Entity_.Payment;
import Entity_.Register;
import Entity_.Student;
import Service_.PaymentService;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import Service_.RegisterService;
import Utility.JavaMailUtil;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MY_PC
 */
public class addCoursePaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form addNewCoursePaymentForm
     */
    Payment p;
    private PaymentService ps = new PaymentService();

    Register r;
    private RegisterService rs = new RegisterService();

    Student s;
    Course c;

    private int sid, cid;
    private String email, cFee;

    Calendar cal = Calendar.getInstance();
    SimpleDateFormat simpletime = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String clockdate = null;
    String clocktime = null;

    public addCoursePaymentForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        clock();
        genarateB.setVisible(false);
    }

    /**
     * view date and time
     */
    public void clock() {
        new Thread() {
            public void run() {

                while (true) {
                    cal = Calendar.getInstance();
                    clocktime = simpletime.format(cal.getTime());
                    clockdate = dateFormat.format(cal.getTime());
                    time.setText(clocktime);
                    date.setText(clockdate);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(addStudentRegistrationPaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        studentName = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        paymentPlan = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        courseFee = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        instalment = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Instalment = new javax.swing.JLabel();
        paidAmount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        instalmentB = new javax.swing.JCheckBox();
        addB = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        clearB = new javax.swing.JButton();
        genarateB = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        studentId = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        idLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentName.setBackground(new java.awt.Color(204, 204, 204));
        studentName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        studentName.setOpaque(true);
        jPanel2.add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 210, 20));

        jLabel25.setBackground(new java.awt.Color(10, 38, 126));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 55));
        jLabel25.setText("Student Name");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 210, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 55));
        jLabel24.setText("Course");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 210, 30));

        course.setBackground(new java.awt.Color(204, 204, 204));
        course.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        course.setOpaque(true);
        jPanel2.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 55));
        jLabel26.setText("Payment Plan");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 210, 30));

        paymentPlan.setBackground(new java.awt.Color(204, 204, 204));
        paymentPlan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        paymentPlan.setOpaque(true);
        jPanel2.add(paymentPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 210, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 55));
        jLabel27.setText("Balance");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 210, 30));

        courseFee.setBackground(new java.awt.Color(204, 204, 204));
        courseFee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        courseFee.setOpaque(true);
        jPanel2.add(courseFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 180, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 55));
        jLabel2.setText("Rs:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        instalment.setBackground(new java.awt.Color(204, 204, 204));
        instalment.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        instalment.setText("00.0");
        instalment.setOpaque(true);
        jPanel2.add(instalment, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 180, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 55));
        jLabel3.setText("Rs:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 55));
        jLabel28.setText("Course Fee");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 210, 30));

        Instalment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Instalment.setForeground(new java.awt.Color(51, 51, 55));
        Instalment.setText("Instalment");
        jPanel2.add(Instalment, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 210, 30));

        paidAmount.setBackground(new java.awt.Color(204, 204, 204));
        paidAmount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        paidAmount.setText("00.0");
        paidAmount.setOpaque(true);
        jPanel2.add(paidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 180, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 55));
        jLabel4.setText("Rs:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 55));
        jLabel30.setText("Paid Amount");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 210, 30));

        balance.setBackground(new java.awt.Color(204, 204, 204));
        balance.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        balance.setText("00.0");
        balance.setOpaque(true);
        jPanel2.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 180, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 55));
        jLabel5.setText("Rs:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        instalmentB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instalmentBMouseClicked(evt);
            }
        });
        instalmentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instalmentBActionPerformed(evt);
            }
        });
        jPanel2.add(instalmentB, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, -1, 20));

        addB.setBackground(new java.awt.Color(69, 70, 71));
        addB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addB.setForeground(new java.awt.Color(255, 255, 255));
        addB.setText("ADD");
        addB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });
        jPanel2.add(addB, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 120, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel15.setToolTipText(" Back");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 50, 40));

        clearB.setBackground(new java.awt.Color(69, 70, 71));
        clearB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearB.setForeground(new java.awt.Color(255, 255, 255));
        clearB.setText("CLEAR");
        clearB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBActionPerformed(evt);
            }
        });
        jPanel2.add(clearB, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 120, 30));

        genarateB.setBackground(new java.awt.Color(153, 153, 153));
        genarateB.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        genarateB.setForeground(new java.awt.Color(0, 51, 204));
        genarateB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_print_36px_1.png"))); // NOI18N
        genarateB.setToolTipText("Print");
        genarateB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        genarateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genarateBActionPerformed(evt);
            }
        });
        jPanel2.add(genarateB, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 70, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1020, 440));

        jPanel1.setBackground(new java.awt.Color(51, 52, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("X");
        jLabel32.setToolTipText("close");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-");
        jLabel22.setToolTipText("minimize");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 30, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 230, 230));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cheap_2_98px.png"))); // NOI18N
        jLabel6.setText("NSBM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setText("Student.Pay.Mgt System");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 230, 230));
        jLabel8.setText("Stu.Course.Payment");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 520, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_30px.png"))); // NOI18N
        jLabel1.setToolTipText("Search");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, 40));

        search.setBackground(new java.awt.Color(51, 52, 54));
        search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(240, 240, 240));
        search.setBorder(null);
        search.setOpaque(false);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 280, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 280, 20));

        studentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studentId.setForeground(new java.awt.Color(240, 240, 240));
        studentId.setText("Student ID");
        jPanel1.add(studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        date.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(230, 230, 230));
        date.setText("Date");
        date.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(230, 230, 230));
        jLabel13.setText("|");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 20, -1));

        time.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(230, 230, 230));
        time.setText("Time");
        time.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 90, -1));

        idLable.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(idLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 180, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void instalmentBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instalmentBMouseClicked

    }//GEN-LAST:event_instalmentBMouseClicked

    /**
     * instalmentB action
     *
     * @param evt
     */
    private void instalmentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instalmentBActionPerformed
        p = new Payment();
        r = new Register();
        s = new Student();

        if (!studentName.getText().equals("") && instalmentB.isSelected()) {

            if (paidAmount.getText().equals(courseFee.getText())) {

                JOptionPane.showMessageDialog(null, studentName.getText() + " is complited course payments");
                instalmentB.setSelected(false);

            } else if (!paidAmount.equals("00.0")) {

                p.setInstalment(Float.valueOf(instalment.getText()));
                p.setPaidAmount(Float.valueOf(paidAmount.getText()));

                //view paid amount
                paidAmount.setText(String.valueOf(ps.viewPaidAmount(p)));

            } else {
                paidAmount.setText(instalment.getText());
            }

            r.setCourseFee(Float.valueOf(courseFee.getText()));
            p.setPaidAmount(Float.valueOf(paidAmount.getText()));

            s.setRegister(r);
            s.setPayment(p);
            //view balance
            balance.setText(String.valueOf(ps.viewBalance(s)));

        } else if (!studentName.equals("") && !instalmentB.isSelected()) {

            //check payment
            if (ps.checkPayment(search.getText())) {

                //search payment details                                 
                Payment p = ps.getPaidAmount(search.getText());

                paidAmount.setText(String.valueOf(p.getPaidAmount()));
                balance.setText(String.valueOf(p.getBalance()));

            } else {

                paidAmount.setText("00.0");
                balance.setText("00.0");

            }

        } else {
            JOptionPane.showMessageDialog(null, "Search a student");
            instalmentB.setSelected(false);
        }
    }//GEN-LAST:event_instalmentBActionPerformed

    /**
     * add course payment
     *
     * @param evt
     */
    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        p = new Payment();

        if (studentName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Search a student");
        } else if (!instalmentB.isSelected()) {
            JOptionPane.showMessageDialog(null, "Need a course payment");
        } else {
            p.setSid(sid);
            p.setCid(cid);
            p.setInstalment(Float.valueOf(instalment.getText()));
            p.setPaidAmount(Float.valueOf(paidAmount.getText()));
            p.setBalance(Float.valueOf(balance.getText()));
            p.setDate(date.getText());
            p.setTime(time.getText());

            ps.addCoursePayment(p);

            // send payment email`    
            try {
                JavaMailUtil.sendPaymentMail(email, cFee, instalment.getText(), paidAmount.getText(), balance.getText());
            } catch (Exception ex) {
                Logger.getLogger(addNewStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            genarateB.setVisible(true);
        }
    }//GEN-LAST:event_addBActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(addCoursePaymentForm.ICONIFIED);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        studentPaymentForm studentPaymentForm = new studentPaymentForm();
        studentPaymentForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * search student,course,register details and payment details
     *
     * @param evt
     */
    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        c = new Course();
        r = new Register();
        s = new Student();

        if (!search.getText().equals("")) {

            //check student register payment
            if (rs.checkStudentRegistrationPayment(search.getText())) {

                idLable.setText("");

                try {

                    //search student,course,register details
                    Student s = ps.search(search.getText());

                    studentName.setText(s.getsName());
                    course.setText(s.getCourse().getaCourseName());
                    paymentPlan.setText(s.getRegister().getPaymentPlan());
                    courseFee.setText(String.valueOf(s.getRegister().getCourseFee()));

                    sid = s.getSid();
                    cid = s.getCourse().getCid();
                    email = s.getEmail();
                    cFee = (String.valueOf(s.getRegister().getCourseFee()));

                    if (ps.checkPayment(search.getText())) {
                        //search payment details                     
                        Payment p = ps.getPaidAmount(search.getText());

                        paidAmount.setText(String.valueOf(p.getPaidAmount()));
                        balance.setText(String.valueOf(p.getBalance()));
                    } else {

                        paidAmount.setText("00.0");
                        balance.setText("00.0");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                c.setaCourseName(course.getText());
                r.setPaymentPlan(paymentPlan.getText());

                s.setCourse(c);
                s.setRegister(r);

                //view instalment
                instalment.setText(String.valueOf(ps.viewInstalment(s)));

            } else {
                idLable.setText("Not a Registed Student ID");
                clear();
            }

        } else {
            search.setText("");
            idLable.setText("");
            clear();
        }
    }//GEN-LAST:event_searchKeyReleased

    private void clearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBActionPerformed
        search.setText("");
        idLable.setText("");
        clear();
    }//GEN-LAST:event_clearBActionPerformed

    private void genarateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genarateBActionPerformed

        paymentReceiptForm now = new paymentReceiptForm();
        now.setVisible(true);

        now.studentName.setText(studentName.getText());
        now.courseName.setText(course.getText());
        now.paymentPlan.setText(paymentPlan.getText());
        now.courseFee.setText(courseFee.getText());
        now.paidAmount.setText(paidAmount.getText());
        now.balance.setText(balance.getText());

        genarateB.setVisible(false);

        search.setText("");
        idLable.setText("");
        clear();
    }//GEN-LAST:event_genarateBActionPerformed

    /**
     * clear fields
     */
    public void clear() {

//        search.setText("");
//        idLable.setText("");
        studentName.setText("");
        course.setText("");
        paymentPlan.setText("");
        courseFee.setText("");
        instalmentB.setSelected(false);
        instalment.setText("00.0");
        paidAmount.setText("00.0");
        balance.setText("00.0");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCoursePaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCoursePaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCoursePaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCoursePaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCoursePaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Instalment;
    private javax.swing.JButton addB;
    private javax.swing.JLabel balance;
    private javax.swing.JButton clearB;
    private javax.swing.JLabel course;
    private javax.swing.JLabel courseFee;
    private javax.swing.JLabel date;
    private javax.swing.JButton genarateB;
    private javax.swing.JLabel idLable;
    private javax.swing.JLabel instalment;
    private javax.swing.JCheckBox instalmentB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel paidAmount;
    private javax.swing.JLabel paymentPlan;
    private javax.swing.JTextField search;
    private javax.swing.JLabel studentId;
    private javax.swing.JLabel studentName;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
