/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_;

import Entity_.Student;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Service_.StudentService;
import Utility.JavaMailUtil;
import View_.subInterf.oneOrMoreFieldEmpty_new;
import com.barcodelib.barcode.Linear;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;

/**
 *
 * @author MY_PC
 */
public class addNewStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form addNewCoursePaymentForm
     */
    Student s;
    private StudentService ss = new StudentService();
    String filename = null;
    byte[] barcodeimage = null;
    int nextid;
    String barcodepath = "C:\\Users\\MY_PC\\Documents\\NetBeansProjects\\EMP_Mgt_System\\Barcode\\Student\\";

    String imagePath, gender;

    public addNewStudentForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        branch = new javax.swing.JComboBox();
        academicYear = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        addB = new javax.swing.JButton();
        browseB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        addb = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        trusteeName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 52, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("X");
        jLabel32.setToolTipText("close");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 30, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-");
        jLabel22.setToolTipText("minimize");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 30, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 230, 230));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_student_registration_88px_1.png"))); // NOI18N
        jLabel6.setText("NSBM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setText("Student.Pay.Mgt System");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 170, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 230, 230));
        jLabel8.setText("Stu.Registration");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 350, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 240));

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 55));
        jLabel33.setText("First Name");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 220, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 55));
        jLabel35.setText("Last Name");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 220, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 55));
        jLabel36.setText("Age");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 220, 30));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 55));
        jLabel37.setText("Trustee Name");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 220, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 55));
        jLabel38.setText("Sex");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 220, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 55));
        jLabel39.setText("Picture");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 220, 30));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 55));
        jLabel41.setText("Address");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 200, 30));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 51, 55));
        jLabel42.setText("Branch");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 220, 30));
        jPanel3.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 250, -1));
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 250, -1));
        jPanel3.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 250, -1));
        jPanel3.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 250, -1));
        jPanel3.add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 250, -1));
        jPanel3.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 250, -1));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane3.setViewportView(address);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 250, 120));

        female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        female.setText(" Female");
        female.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleMouseClicked(evt);
            }
        });
        jPanel3.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 100, -1));

        male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        male.setText(" Male");
        male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleMouseClicked(evt);
            }
        });
        jPanel3.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, -1));

        branch.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        branch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Branch", "Malabe", "Kandy", "Jafna" }));
        jPanel3.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 210, -1));

        academicYear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        academicYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Year", "2020", "2021", "2022", "2023", "2024" }));
        jPanel3.add(academicYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 210, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 55));
        jLabel16.setText("Course");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 220, 30));

        course.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        course.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selact Course", "BScIT", "BScCV", "BScME", "BScQS", "BBAAF", "BBABA", "BBAMM" }));
        jPanel3.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 210, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 55));
        jLabel24.setText("NIC");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 220, 30));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 51, 55));
        jLabel43.setText("Telephone");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 220, 30));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 51, 55));
        jLabel45.setText("Email");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 220, 30));

        picture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        picture.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 140, 100));

        addB.setText("ADD");
        jPanel3.add(addB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 580, -1, -1));

        browseB.setBackground(new java.awt.Color(69, 70, 71));
        browseB.setForeground(new java.awt.Color(255, 255, 255));
        browseB.setText("Browse");
        browseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBActionPerformed(evt);
            }
        });
        jPanel3.add(browseB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 55));
        jLabel9.setText("Acadamic Year");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 220, 30));

        addb.setBackground(new java.awt.Color(69, 70, 71));
        addb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addb.setForeground(new java.awt.Color(255, 255, 255));
        addb.setText("ADD");
        addb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });
        jPanel3.add(addb, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 120, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel15.setToolTipText(" Back");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 50, 40));
        jPanel3.add(trusteeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 250, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1120, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(addNewStudentForm.ICONIFIED);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel32MouseClicked

    /**
     * add new student
     *
     * @param evt
     */
    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        s = new Student();
        ss.nextId(s);
        nextid = s.getSid() + 1;
        System.out.println(nextid);

        //Generate a Barcode
        try {

            Linear barcode = new Linear();
            barcode.setType(Linear.CODE128B);
            barcode.setData(String.valueOf(s.getSid()));
            barcode.setI(11.0f);
            barcode.renderBarcode(barcodepath + nextid + ".png");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            filename = barcodepath + nextid + ".png";
            File img = new File(filename);
            FileInputStream fis = new FileInputStream(img);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for (int readNum; (readNum = fis.read(buf)) != -1;) {

                bos.write(buf, 0, readNum);
            }
            barcodeimage = bos.toByteArray();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

        if (male.isSelected()) {
            gender = "Male";
        } else if (female.isSelected()) {
            gender = "Female";
        } else {
            gender = "";
        }

        if (firstName.getText().equals("") || lastName.getText().equals("") || age.getText().equals("")) {
            //JOptionPane.showMessageDialog(null, "One or more fields are empty");
            oneOrMoreFieldEmpty_new var = new oneOrMoreFieldEmpty_new();
            var.setVisible(true);
        } else if (nic.getText().equals("") || gender.equals("") || telephone.getText().equals("") || email.getText().equals("")) {
            //JOptionPane.showMessageDialog(null, "One or more fields are empty");
            oneOrMoreFieldEmpty_new var = new oneOrMoreFieldEmpty_new();
            var.setVisible(true);
        } else if (!email.getText().matches("^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$")) {
            JOptionPane.showMessageDialog(null, "Invalid Email Address", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (imagePath == null) {
            JOptionPane.showMessageDialog(null, "No image");
        } else if (address.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No address");
        } else if (branch.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Plz select a branch");
        } else if (trusteeName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No trustee name");
        } else if (course.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Plz select a course");
        } else if (academicYear.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Plz select a academic year");
        } else {
            s.setsName(firstName.getText() + " " + lastName.getText());
            s.setAge(age.getText());
            s.setNic(nic.getText());
            s.setGender(gender);
            s.setTelephone(telephone.getText());
            s.setEmail(email.getText());
            s.setImagePath(imagePath);
            s.setAddress(address.getText());
            s.setTName(trusteeName.getText());
            s.setBranch(branch.getSelectedItem().toString());
            s.setaYear(academicYear.getSelectedItem().toString());
            s.setCid(course.getSelectedIndex());
            s.setBarcode(barcodeimage);

            ss.save(s);

            //send fee structure email
            try {
                JavaMailUtil.sendFeeStructureMail(email.getText(), course.getSelectedItem().toString());
            } catch (Exception ex) {
                Logger.getLogger(addNewStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            clear();
        }
    }//GEN-LAST:event_addbActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        studentRegistrationForm nf = new studentRegistrationForm();
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    public ImageIcon resizePic(String picPath) {
        ImageIcon myImg = new ImageIcon(picPath);
        Image img = myImg.getImage().getScaledInstance(picture.getWidth(), picture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon myPicture = new ImageIcon(img);
        return myPicture;
    }

    /**
     * browseB action
     *
     * @param evt
     */
    private void browseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter fnef = new FileNameExtensionFilter("*.image", "jpg", "png", "gif");
        fc.addChoosableFileFilter(fnef);

        int fileState = fc.showSaveDialog(null);

        if (fileState == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fc.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            imagePath = path;

            picture.setIcon(resizePic(path));
        } else if (fileState == JFileChooser.CANCEL_OPTION) {
            System.out.println("no image selected");
        }
    }//GEN-LAST:event_browseBActionPerformed

    private void maleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleMouseClicked
        female.setSelected(false);
    }//GEN-LAST:event_maleMouseClicked

    private void femaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleMouseClicked
        male.setSelected(false);
    }//GEN-LAST:event_femaleMouseClicked

    /**
     * clear fields
     */
    public void clear() {

        firstName.setText("");
        lastName.setText("");
        age.setText("");
        nic.setText("");
        male.setSelected(false);
        female.setSelected(false);
        telephone.setText("");
        email.setText("");
        picture.setIcon(null);
        address.setText("");
        trusteeName.setText("");
        branch.setSelectedIndex(0);
        course.setSelectedIndex(0);
        academicYear.setSelectedIndex(0);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox academicYear;
    private javax.swing.JButton addB;
    private javax.swing.JButton addb;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox branch;
    private javax.swing.JButton browseB;
    private javax.swing.JComboBox course;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastName;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField nic;
    private javax.swing.JLabel picture;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextField trusteeName;
    // End of variables declaration//GEN-END:variables
}
