                                           /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_;

import Entity_.Course;
import Entity_.Register;
import Entity_.Student;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import Service_.RegisterService;
import Service_.StudentService;
import Utility.JavaMailUtil;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MY_PC
 */
public class addStudentRegistrationPaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form addNewCoursePaymentForm
     */
    
    Student s;
    private StudentService ss = new StudentService();
    
    Register r;
    private RegisterService rs = new RegisterService();
    
    Course c;
    
    private int sid,cid;

    Calendar cal = Calendar.getInstance();
    SimpleDateFormat simpletime = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");    
    String clockdate = null;
    String clocktime = null;
    
    public addStudentRegistrationPaymentForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        clock();
    }
    
    
    /**
     * view date and time
     */
    public void clock() {
        new Thread() {
            public void run() {

                while (true) {
                    cal = Calendar.getInstance();
                    clocktime = simpletime.format(cal.getTime());
                    clockdate = dateFormat.format(cal.getTime());
                    time.setText(clocktime);
                    date.setText(clockdate);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(addStudentRegistrationPaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        paymentPlan = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        studentName = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        academicYear = new javax.swing.JLabel();
        registationFee = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        courseFee = new javax.swing.JLabel();
        registationFeeB = new javax.swing.JCheckBox();
        otherFee = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        libraryFee = new javax.swing.JLabel();
        libraryFeeB = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        developmentFee = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        developmentFeeB = new javax.swing.JCheckBox();
        otherFeeB = new javax.swing.JCheckBox();
        viewB1 = new javax.swing.JButton();
        addB = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        addB1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        studentId = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        idLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 55));
        jLabel25.setText("Student Name");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, 30));

        paymentPlan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        paymentPlan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selact Payment Plan", "Plan A", "Plan B", "Plan C", "Plan D" }));
        jPanel2.add(paymentPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 210, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 55));
        jLabel26.setText("Select a payment Plan");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 210, 30));

        studentName.setBackground(new java.awt.Color(204, 204, 204));
        studentName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        studentName.setOpaque(true);
        jPanel2.add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 210, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 55));
        jLabel23.setText("Email");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 210, 30));

        email.setBackground(new java.awt.Color(204, 204, 204));
        email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        email.setOpaque(true);
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 210, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 55));
        jLabel24.setText("Course");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 210, 30));

        course.setBackground(new java.awt.Color(204, 204, 204));
        course.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        course.setOpaque(true);
        jPanel2.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 210, 20));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 55));
        jLabel21.setText("Academic Year");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 210, 30));

        academicYear.setBackground(new java.awt.Color(204, 204, 204));
        academicYear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        academicYear.setOpaque(true);
        jPanel2.add(academicYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 210, 20));

        registationFee.setBackground(new java.awt.Color(204, 204, 204));
        registationFee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        registationFee.setText("10000.00");
        registationFee.setOpaque(true);
        jPanel2.add(registationFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 180, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 55));
        jLabel3.setText("Rs:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 55));
        jLabel29.setText("Registation Fee");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 55));
        jLabel2.setText("Rs:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 55));
        jLabel27.setText("Course Fee");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 210, 30));

        courseFee.setBackground(new java.awt.Color(204, 204, 204));
        courseFee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        courseFee.setOpaque(true);
        jPanel2.add(courseFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 180, 20));

        registationFeeB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registationFeeBMouseClicked(evt);
            }
        });
        jPanel2.add(registationFeeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, -1, -1));

        otherFee.setBackground(new java.awt.Color(204, 204, 204));
        otherFee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        otherFee.setText("1000.00");
        otherFee.setOpaque(true);
        jPanel2.add(otherFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 180, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 55));
        jLabel9.setText("Rs:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 55));
        jLabel33.setText("Other Fee");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 210, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 55));
        jLabel31.setText("Library Fee");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 55));
        jLabel5.setText("Rs:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, -1, -1));

        libraryFee.setBackground(new java.awt.Color(204, 204, 204));
        libraryFee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        libraryFee.setText("1000.00");
        libraryFee.setOpaque(true);
        jPanel2.add(libraryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 180, -1));
        jPanel2.add(libraryFeeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 55));
        jLabel10.setText("Rs:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        developmentFee.setBackground(new java.awt.Color(204, 204, 204));
        developmentFee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        developmentFee.setText("5000.00");
        developmentFee.setOpaque(true);
        jPanel2.add(developmentFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 180, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 55));
        jLabel30.setText("Development Fee");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 210, 30));
        jPanel2.add(developmentFeeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, -1, -1));
        jPanel2.add(otherFeeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, -1, -1));

        viewB1.setBackground(new java.awt.Color(69, 70, 71));
        viewB1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewB1.setForeground(new java.awt.Color(255, 255, 255));
        viewB1.setText("View");
        viewB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewB1ActionPerformed(evt);
            }
        });
        jPanel2.add(viewB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 80, 30));

        addB.setBackground(new java.awt.Color(69, 70, 71));
        addB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addB.setForeground(new java.awt.Color(255, 255, 255));
        addB.setText("ADD");
        addB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });
        jPanel2.add(addB, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 120, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel15.setToolTipText(" Back");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 50, 40));

        addB1.setBackground(new java.awt.Color(69, 70, 71));
        addB1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addB1.setForeground(new java.awt.Color(255, 255, 255));
        addB1.setText("CLEAR");
        addB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addB1ActionPerformed(evt);
            }
        });
        jPanel2.add(addB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 440, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1120, 490));

        jPanel1.setBackground(new java.awt.Color(51, 52, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("X");
        jLabel32.setToolTipText("close");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 30, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-");
        jLabel22.setToolTipText("minimize");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 30, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 230, 230));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cheap_2_98px.png"))); // NOI18N
        jLabel6.setText("NSBM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setText("Student.Pay.Mgt System");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 230, 230));
        jLabel8.setText("Stu.Registration.Payment");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 420, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_30px.png"))); // NOI18N
        jLabel1.setToolTipText("Search");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, 40));

        search.setBackground(new java.awt.Color(51, 52, 54));
        search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(240, 240, 240));
        search.setBorder(null);
        search.setOpaque(false);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 280, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 280, 20));

        studentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studentId.setForeground(new java.awt.Color(240, 240, 240));
        studentId.setText("Student ID");
        jPanel1.add(studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        date.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(230, 230, 230));
        date.setText("Date");
        date.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(230, 230, 230));
        jLabel13.setText("|");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 20, -1));

        time.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(230, 230, 230));
        time.setText("Time");
        time.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 90, -1));

        idLable.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(idLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 130, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(studentForm.ICONIFIED);       
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void registationFeeBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registationFeeBMouseClicked

    }//GEN-LAST:event_registationFeeBMouseClicked

    
    /**
     * view total course fee
     * @param evt 
     */
    private void viewB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewB1ActionPerformed
       r = new Register();
       c = new Course();
       s = new Student();

            c.setaCourseName(course.getText());
            r.setPaymentPlan(paymentPlan.getSelectedItem().toString());
            
            s.setCourse(c);
            s.setRegister(r);

            courseFee.setText(String.valueOf(rs.viewCourseFee(s)));
    }//GEN-LAST:event_viewB1ActionPerformed

    /**
     * add student registration payment
     * @param evt 
     */
    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        
        r=new Register();
        
            if(studentName.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Search a student");
            }
            else if(rs.checkStudentRegistrationPayment(search.getText())){
                JOptionPane.showMessageDialog(null, "already registed");
            }
            else if(paymentPlan.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Select a payment plan");
            }
            else if(!registationFeeB.isSelected()){
                JOptionPane.showMessageDialog(null, "Need a regisation fee");
            }
            else if(!libraryFeeB.isSelected()){
                JOptionPane.showMessageDialog(null, "Need a library fee");
            }
            else if(!developmentFeeB.isSelected()){
                JOptionPane.showMessageDialog(null, "Need a development fee");
            }
            else if(!otherFeeB.isSelected()){
                JOptionPane.showMessageDialog(null, "Need a other fee");
            }
            else{
                r.setSid(sid);
                r.setCid(cid);
                r.setPaymentPlan(paymentPlan.getSelectedItem().toString());
                r.setCourseFee(Float.valueOf(courseFee.getText()));
                r.setRegistationFee(Float.valueOf(registationFee.getText()));
                r.setLibraryFee(Float.valueOf(libraryFee.getText()));
                r.setDevelopmentFee(Float.valueOf(developmentFee.getText()));
                r.setOtherFee(Float.valueOf(otherFee.getText()));
                r.setDate(date.getText());

                rs.addStudentRegitrationPayment(r);

            // send registration email`    
            try {
                JavaMailUtil.sendRegistationMail(email.getText());
            } catch (Exception ex) {
                Logger.getLogger(addNewStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
                search.setText("");
                idLable.setText(""); 
                clear();
            }
        
           
    }//GEN-LAST:event_addBActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        studentPaymentForm studentPaymentForm=new studentPaymentForm();
        studentPaymentForm.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * search student details and course details
     * @param evt 
     */
    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased

        if(!search.getText().equals("")){
            
            //check student
            if(ss.checkStudent(search.getText())){
                
                idLable.setText(""); 
                
                Student s = rs.search(search.getText());

                    try {

                            studentName.setText(s.getsName());
                            email.setText(s.getEmail());
                            academicYear.setText(s.getaYear());
                            course.setText(s.getCourse().getaCourseName());

                            sid=s.getSid();
                            cid=s.getCourse().getCid();           

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    
                //check student registration payment   
                if(rs.checkStudentRegistrationPayment(search.getText())){

                    JOptionPane.showMessageDialog(null, "already registed");

                }
                else{}
            }else{
                idLable.setText("Not a Student ID");
                clear();
            }
               
        }else{
            search.setText("");
            idLable.setText("");
            clear();
        }
            
    }//GEN-LAST:event_searchKeyReleased

    private void addB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addB1ActionPerformed
        search.setText("");
        idLable.setText("");
        clear();
        search.requestFocus();
    }//GEN-LAST:event_addB1ActionPerformed

    
    /**
     * clear fields
     */
     public void clear(){
         
//        search.setText("");
//        idLable.setText("");
        studentName.setText("");
        email.setText("");
        course.setText("");
        academicYear.setText("");
        paymentPlan.setSelectedIndex(0);
        courseFee.setText("");
        registationFeeB.setSelected(false);
        libraryFeeB.setSelected(false);
        developmentFeeB.setSelected(false);
        otherFeeB.setSelected(false);
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudentRegistrationPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudentRegistrationPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudentRegistrationPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudentRegistrationPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudentRegistrationPaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academicYear;
    private javax.swing.JButton addB;
    private javax.swing.JButton addB1;
    private javax.swing.JLabel course;
    private javax.swing.JLabel courseFee;
    private javax.swing.JLabel date;
    private javax.swing.JLabel developmentFee;
    private javax.swing.JCheckBox developmentFeeB;
    private javax.swing.JLabel email;
    private javax.swing.JLabel idLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel libraryFee;
    private javax.swing.JCheckBox libraryFeeB;
    private javax.swing.JLabel otherFee;
    private javax.swing.JCheckBox otherFeeB;
    private javax.swing.JComboBox paymentPlan;
    private javax.swing.JLabel registationFee;
    private javax.swing.JCheckBox registationFeeB;
    private javax.swing.JTextField search;
    private javax.swing.JLabel studentId;
    private javax.swing.JLabel studentName;
    private javax.swing.JLabel time;
    private javax.swing.JButton viewB1;
    // End of variables declaration//GEN-END:variables
}
