/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_;

import Entity_.Employee;
import Service_.EmployeeService;
import View_.login;
import java.awt.Image;
import static java.lang.Thread.sleep;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY_PC
 */
public class attendance extends javax.swing.JFrame {

    Employee emp;
    private EmployeeService empSrv = new EmployeeService();
    Calendar cal = Calendar.getInstance();
    Calendar cal2 = new GregorianCalendar();
    SimpleDateFormat simpletime = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date currenttime;
    Date endtime;
    Date starttime;
    Date halftime;
    DefaultTableModel model = new DefaultTableModel();
    String attend = null;
    String clockdate = null;
    String clocktime = null;
    int num = 0;
    boolean choice;

    public attendance() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        //model = (DefaultTableModel) table.getModel();
        name.setEditable(false);
        clock();
        id.requestFocus();
        //timesetting();
    }

    public void clock() {
        new Thread() {
            public void run() {

                while (true) {
                    cal = Calendar.getInstance();
                    clocktime = simpletime.format(cal.getTime());
                    clockdate = dateFormat.format(cal.getTime());
                    time.setText(clocktime);
                    date.setText(clockdate);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }.start();
    }

    public void timesetting() {
        try {
            halftime = simpletime.parse("12:00:00");
            endtime = simpletime.parse("18:00:00");
            starttime = simpletime.parse("08:00:00");
        } catch (ParseException ex) {
            Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            currenttime = simpletime.parse(clocktime);
        } catch (ParseException ex) {
            Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (currenttime.compareTo(starttime) < 0) {
            attend = "Full Day";
            inscan.setEnabled(true);
            finalize.setEnabled(false);
        } else if (currenttime.compareTo(halftime) < 0) {
            attend = "Half Day";
            inscan.setEnabled(true);
            finalize.setEnabled(false);
        } else {
            attend = "Abcent";
            inscan.setEnabled(false);
            finalize.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attendancePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        outscan = new javax.swing.JButton();
        finalize = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        inscan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        staffLbl = new javax.swing.JLabel();
        lectureLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendancePanel.setBackground(new java.awt.Color(250, 250, 250));
        attendancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 53, 54), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        date.setForeground(new java.awt.Color(51, 52, 54));
        date.setText("Date");
        date.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 52, 54));
        jLabel13.setText("|");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 20, -1));

        time.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        time.setForeground(new java.awt.Color(51, 52, 54));
        time.setText("Time");
        time.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, -1));

        image.setBackground(new java.awt.Color(255, 255, 255));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_attach_resume_male_125px.png"))); // NOI18N
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 52, 53)));
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 160, 140));

        id.setBackground(new java.awt.Color(250, 250, 250));
        id.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        id.setBorder(null);
        id.setOpaque(false);
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 190, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 190, 10));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 52, 54));
        jLabel20.setText("ID");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 40, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 52, 54));
        jLabel21.setText("Name");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 80, -1));

        name.setBackground(new java.awt.Color(250, 250, 250));
        name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name.setBorder(null);
        name.setOpaque(false);
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 190, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 190, 10));

        outscan.setBackground(new java.awt.Color(69, 70, 71));
        outscan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        outscan.setForeground(new java.awt.Color(255, 255, 255));
        outscan.setText("Log out Scan");
        outscan.setToolTipText("Scan");
        outscan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        outscan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outscanActionPerformed(evt);
            }
        });
        jPanel1.add(outscan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 130, 40));

        finalize.setBackground(new java.awt.Color(243, 32, 32));
        finalize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalize.setForeground(new java.awt.Color(255, 255, 255));
        finalize.setText("Finalize");
        finalize.setToolTipText("Finalize");
        finalize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeActionPerformed(evt);
            }
        });
        jPanel1.add(finalize, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 270, 50));

        jLabel4.setForeground(new java.awt.Color(51, 52, 54));
        jLabel4.setText("Show Table");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 60));

        image1.setBackground(new java.awt.Color(255, 255, 255));
        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_show_property_35px_1.png"))); // NOI18N
        image1.setToolTipText("Show Table");
        image1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        image1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image1MouseClicked(evt);
            }
        });
        jPanel1.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 40, 70));

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_search_30px_1.png"))); // NOI18N
        search.setToolTipText("Scan");
        search.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 40, 40));

        inscan.setBackground(new java.awt.Color(69, 70, 71));
        inscan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        inscan.setForeground(new java.awt.Color(255, 255, 255));
        inscan.setText("Log in Add");
        inscan.setToolTipText("Scan");
        inscan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inscan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscanActionPerformed(evt);
            }
        });
        jPanel1.add(inscan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 130, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 40));

        attendancePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 360, 530));

        jPanel2.setBackground(new java.awt.Color(51, 52, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_attendance_96px_1.png"))); // NOI18N
        jLabel2.setText("NSBM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 110));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 230, 230));
        jLabel3.setText("Payroll System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 120, 30));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setText("Attendance.check");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 330, 60));

        staffLbl.setBackground(new java.awt.Color(73, 74, 75));
        staffLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        staffLbl.setForeground(new java.awt.Color(230, 230, 230));
        staffLbl.setText("Staffs");
        staffLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffLbl.setOpaque(true);
        staffLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                staffLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                staffLblMouseExited(evt);
            }
        });
        jPanel2.add(staffLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 210, 30));

        lectureLbl.setBackground(new java.awt.Color(51, 52, 54));
        lectureLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lectureLbl.setForeground(new java.awt.Color(230, 230, 230));
        lectureLbl.setText("Lectures");
        lectureLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lectureLbl.setOpaque(true);
        lectureLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lectureLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lectureLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lectureLblMouseExited(evt);
            }
        });
        jPanel2.add(lectureLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_go_back_37px_1.png"))); // NOI18N
        jLabel6.setToolTipText(" Back");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 40, 40));

        attendancePanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1120, 390));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(54, 54, 54));
        jLabel27.setText("-");
        jLabel27.setToolTipText("minimize");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        attendancePanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 30, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(54, 54, 54));
        jLabel26.setText("X");
        jLabel26.setToolTipText("close");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        attendancePanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 30, 30));

        getContentPane().add(attendancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeActionPerformed
        timesetting();
        emp = new Employee();

        emp.setAttenddate(clockdate);

        empSrv.nextId(emp, "staff");
        emp.setStatus("staff");
        empSrv.checkAbsent(emp);

        empSrv.nextId(emp, "lecturer");
        emp.setStatus("lecturer");
        empSrv.checkAbsent(emp);
    }//GEN-LAST:event_finalizeActionPerformed

    private void image1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image1MouseClicked
        // TODO add your handling code here:
        attendanceTable attablobj = new attendanceTable();
        attablobj.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_image1MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void staffLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffLblMouseClicked
        lblSetColor(staffLbl);
        lblResetColor(lectureLbl);
        choice = true;

        jLabel1.setText("S");
    }//GEN-LAST:event_staffLblMouseClicked

    private void staffLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffLblMouseEntered
        //lblSetColor(staffLbl);
    }//GEN-LAST:event_staffLblMouseEntered

    private void staffLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffLblMouseExited
        //lblResetColor(staffLbl);
    }//GEN-LAST:event_staffLblMouseExited

    private void lectureLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectureLblMouseClicked
        lblSetColor(lectureLbl);
        lblResetColor(staffLbl);
        choice = false;

        jLabel1.setText("L");
    }//GEN-LAST:event_lectureLblMouseClicked

    private void lectureLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectureLblMouseEntered
        //lblSetColor(lectureLbl);
    }//GEN-LAST:event_lectureLblMouseEntered

    private void lectureLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectureLblMouseExited
        //lblResetColor(lectureLbl);
    }//GEN-LAST:event_lectureLblMouseExited

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        emp = new Employee();
        emp.setId(Integer.parseInt(String.valueOf(id.getText().charAt(1))));
        switch (id.getText().charAt(0)) {
            case 'E':
                empSrv.search(emp, "staff");
                break;
            case 'L':
                empSrv.search(emp, "lecturer");
                break;
            default:
                JOptionPane.showMessageDialog(null, "Invalid ID", "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }

        name.setText(emp.getFirstname() + " " + emp.getLastname());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(emp.getImage()).getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH));
        image.setIcon(imageIcon);
    }//GEN-LAST:event_searchActionPerformed

    private void inscanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscanActionPerformed
        timesetting();
        emp.setAttendstatus(attend);
        emp.setAttenddate(clockdate);
        emp.setAttendintime(clocktime);
        emp.setAttendouttime("null");
        switch (id.getText().charAt(0)) {
            case 'E':
                emp.setStatus("staff");
                break;
            case 'L':
                emp.setStatus("lecturer");
                break;
            default:
                JOptionPane.showMessageDialog(null, "Invalid ID", "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }

        empSrv.inAttend(emp);
    }//GEN-LAST:event_inscanActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped

    }//GEN-LAST:event_idKeyTyped

    private void outscanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outscanActionPerformed
        emp.setAttendstatus(attend);
        emp.setAttenddate(clockdate);
        emp.setAttendouttime(clocktime);
        switch (id.getText().charAt(0)) {
            case 'E':
                emp.setStatus("staff");
                break;
            case 'L':
                emp.setStatus("lecturer");
                break;
            default:
                JOptionPane.showMessageDialog(null, "Invalid ID", "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
        empSrv.outAttend(emp);
    }//GEN-LAST:event_outscanActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        process pc = new process();
        pc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyPressed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idKeyPressed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        emp = new Employee();
        emp.setId(Integer.parseInt(String.valueOf(id.getText().charAt(1))));
        switch (id.getText().charAt(0)) {
            case 'E':
                empSrv.search(emp, "staff");
                break;
            case 'L':
                empSrv.search(emp, "lecturer");
                break;
            default:
                JOptionPane.showMessageDialog(null, "Invalid ID", "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }

        name.setText(emp.getFirstname() + " " + emp.getLastname());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(emp.getImage()).getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH));
        image.setIcon(imageIcon);
    }//GEN-LAST:event_idKeyReleased

    public void lblSetColor(JLabel lable) {

        lable.setBackground(new java.awt.Color(73, 74, 75));

    }

    public void lblResetColor(JLabel lable) {

        lable.setBackground(new java.awt.Color(51, 52, 54));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attendancePanel;
    private javax.swing.JLabel date;
    private javax.swing.JButton finalize;
    private javax.swing.JTextField id;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image1;
    private javax.swing.JButton inscan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lectureLbl;
    private javax.swing.JTextField name;
    private javax.swing.JButton outscan;
    private javax.swing.JButton search;
    private javax.swing.JLabel staffLbl;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
