/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class paymentReceiptForm extends javax.swing.JFrame {

    Calendar cal = Calendar.getInstance();
    SimpleDateFormat simpletime = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");    
    String clockdate = null;
    String clocktime = null;
    
    public paymentReceiptForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        clock();
    }

    
    /**
     * view date and time
     */
    public void clock() {
        new Thread() {
            public void run() {

                while (true) {
                    cal = Calendar.getInstance();
                    clocktime = simpletime.format(cal.getTime());
                    clockdate = dateFormat.format(cal.getTime());
                    time.setText(clocktime);
                    date.setText(clockdate);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(addStudentRegistrationPaymentForm.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        pannelprint = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        studentName = new javax.swing.JLabel();
        courseName = new javax.swing.JLabel();
        paymentPlan = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        courseFee = new javax.swing.JLabel();
        paidAmount = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(57, 58, 60));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_print_36px_1.png"))); // NOI18N
        jButton3.setToolTipText("Print");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 40));

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_new_/icons8_close_window_36px_1.png"))); // NOI18N
        jButton4.setToolTipText("Close");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 40));

        jPanel9.setBackground(new java.awt.Color(51, 52, 54));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 90, 170));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 480));

        pannelprint.setBackground(new java.awt.Color(255, 255, 255));
        pannelprint.setForeground(new java.awt.Color(255, 255, 255));
        pannelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("RECEIPT");
        pannelprint.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 90, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Pitipana - Thalagala Rd, Homagama 10200");
        pannelprint.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 250, 30));
        pannelprint.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 490, 20));
        pannelprint.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 460, 20));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel23.setText("CAMPPUS PRIVATE INSTITUTE");
        pannelprint.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 280, 30));

        jLabel1.setText("Student Name :");
        pannelprint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        jLabel2.setText("Date");
        pannelprint.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 40, 30));

        jLabel5.setText("Time");
        pannelprint.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 40, 30));

        jLabel6.setText("Course Name :");
        pannelprint.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 30));

        jLabel7.setText("Payment Plan :");
        pannelprint.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 30));

        jLabel8.setText("Course Fee : ");
        pannelprint.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 30));

        jLabel10.setText("Paid amount :");
        pannelprint.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, 30));

        jLabel11.setText("----------------------------");
        pannelprint.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 150, 30));

        jLabel12.setText("----------------------------");
        pannelprint.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 150, 30));

        jLabel14.setText("Full Balance :");
        pannelprint.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, 30));
        pannelprint.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 110, 30));
        pannelprint.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 150, 30));
        pannelprint.add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 30));
        pannelprint.add(courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, 30));
        pannelprint.add(paymentPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 170, 30));

        jLabel19.setText("----------------------------");
        pannelprint.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 150, 30));

        jLabel20.setText("----------------------------");
        pannelprint.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 150, 30));
        pannelprint.add(courseFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 100, 30));
        pannelprint.add(paidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 110, 30));
        pannelprint.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 150, 30));

        jLabel9.setText("Rs:");
        pannelprint.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, 30));

        jLabel13.setText("Rs:");
        pannelprint.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        jLabel16.setText("Rs:");
        pannelprint.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, 30));

        getContentPane().add(pannelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 580, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * generate payment receipt
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.765,0.75);

                pannelprint.print(g2);

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentReceiptForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel balance;
    public javax.swing.JLabel courseFee;
    public javax.swing.JLabel courseName;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel paidAmount;
    private javax.swing.JPanel pannelprint;
    public javax.swing.JLabel paymentPlan;
    public javax.swing.JLabel studentName;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
