/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_;

import Entity_.Employee;
import Entity_.Salary;
import Entity_.User;
import Entity_.jReportEntity;
import Service_.EmployeeService;
import Service_.SalaryService;
import Service_.jReportService;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author MY_PC
 */
public class salaryCalc extends javax.swing.JFrame {

    Employee emp;
    User u;
    Salary sal;
    private EmployeeService empSrv = new EmployeeService();
    private SalaryService salsrv = new SalaryService();
    boolean choice;
    double v;
    double bsal;
    double gross_salary;
    Calendar cal = Calendar.getInstance();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    jReportEntity jre;
    jReportService jrs = new jReportService();
    PDFJpannel rj = new PDFJpannel();

    /*
    Total Earning = selction + bs + OT
     */
    public salaryCalc() {
        initComponents();
        this.setLocationRelativeTo(null);
        staffpanel.setVisible(true);
        lecturepanel.setVisible(false);
        stafflbl.setBackground(new java.awt.Color(51, 52, 54));
        staffLbl.setVisible(false);
        staffLabl2.setVisible(false);
        leclbl.setVisible(false);
        leclbl2.setVisible(false);
        totEarningS.setEditable(false);
        saveBtn.setEnabled(false);
        srcBtn.setEnabled(false);

    }

    public void clear() {
        EMPIDtxt.setText("");
        firstname.setText("");
        lastname.setText("");
        nationalid.setText("");
        datehired.setText("");
        department.setText("");
        designation.setText("");
        basicsalary.setText("");
        otEarningS.setText("");
        rphEarningS.setText("");
        totEarningS.setText("0.00");
        earningS.setText("");
        selectcomboSE.setSelectedIndex(0);
        textareaSE.setText("");
        sEPF.setText("0.00");
        sETF.setText("0.00");
        totalEarningS.setText("0.00");
        TAlabel.setText("0.00");
        TDlabel.setText("0.00");
        Finallabel.setText("0.00");
        deductionS.setText("");
        selectcomboSD.setSelectedIndex(0);
        textareaSD.setText("");
        earningL.setText("");
        selectcomboLE.setSelectedIndex(0);
        textareaLE.setText("");
        deductionL.setText("");
        selectcomboLD.setSelectedIndex(0);
        textareaLD.setText("");
        totalEarningL.setText("0.00");
        totalDeductionL.setText("0.00");
        totalDeductionL.setText("0.00");
        search.setText("");
        search.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salaryCalcul = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lectlbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stafflbl = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        var = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        srcBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Finallabel = new javax.swing.JLabel();
        TAlabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        TDlabel = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        designation = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        department = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        basicsalary = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        datehired = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        nationalid = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        EMPIDtxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        image = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        calculateBtn = new javax.swing.JButton();
        pictureBrowse1 = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lecturepanel = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        selectcomboLE = new javax.swing.JComboBox<>();
        earningL = new javax.swing.JTextField();
        jSeparator40 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textareaLE = new javax.swing.JTextArea();
        jLabel53 = new javax.swing.JLabel();
        totalEarningL = new javax.swing.JLabel();
        leclbl = new javax.swing.JTextField();
        addLE = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        deductionL = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        textareaLD = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        totalDeductionL = new javax.swing.JLabel();
        selectcomboLD = new javax.swing.JComboBox<>();
        addLD = new javax.swing.JButton();
        leclbl2 = new javax.swing.JTextField();
        staffpanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        totalEarningS = new javax.swing.JLabel();
        earningS = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        totEarningS = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        otEarningS = new javax.swing.JTextField();
        rphEarningS = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        staffLbl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaSE = new javax.swing.JTextArea();
        selectcomboSE = new javax.swing.JComboBox<>();
        addSE = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        totalDeductionS = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        deductionS = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        selectcomboSD = new javax.swing.JComboBox<>();
        addSD = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaSD = new javax.swing.JTextArea();
        staffLabl2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        sEPF = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        sETF = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salaryCalcul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 52, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_get_cash_96px.png"))); // NOI18N
        jLabel2.setText("NSBM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, 90));

        lectlbl.setBackground(new java.awt.Color(51, 52, 54));
        lectlbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lectlbl.setForeground(new java.awt.Color(230, 230, 230));
        lectlbl.setText("Lectures");
        lectlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lectlbl.setOpaque(true);
        lectlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lectlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lectlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lectlblMouseExited(evt);
            }
        });
        jPanel2.add(lectlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 210, 30));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setText("Emp.Salary.Calc");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 290, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 230, 230));
        jLabel4.setText("Payroll System");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, 40));

        stafflbl.setBackground(new java.awt.Color(73, 74, 75));
        stafflbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        stafflbl.setForeground(new java.awt.Color(230, 230, 230));
        stafflbl.setText("Staffs");
        stafflbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stafflbl.setOpaque(true);
        stafflbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stafflblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stafflblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stafflblMouseExited(evt);
            }
        });
        jPanel2.add(stafflbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 210, 30));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("-");
        jLabel47.setToolTipText("minimize");
        jLabel47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 30, 30));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("X");
        jLabel48.setToolTipText("close");
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 30, 30));

        var.setBackground(new java.awt.Color(51, 52, 54));
        var.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var.setForeground(new java.awt.Color(255, 255, 255));
        var.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        var.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(var, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 30, 40));

        search.setBackground(new java.awt.Color(51, 52, 54));
        search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(240, 240, 240));
        search.setBorder(null);
        search.setOpaque(false);
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 250, 40));

        srcBtn.setBackground(new java.awt.Color(51, 52, 54));
        srcBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        srcBtn.setForeground(new java.awt.Color(51, 52, 54));
        srcBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_search_30px.png"))); // NOI18N
        srcBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        srcBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        srcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcBtnActionPerformed(evt);
            }
        });
        jPanel2.add(srcBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 50, 40));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 280, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel5.setToolTipText(" Back");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 430, 50, 40));

        salaryCalcul.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 260));

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 45, 45));
        jLabel13.setText("Salary after Calculations");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, 210, -1));

        Finallabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Finallabel.setForeground(new java.awt.Color(240, 45, 45));
        Finallabel.setText("0.00");
        jPanel3.add(Finallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 700, 80, -1));

        TAlabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        TAlabel.setForeground(new java.awt.Color(60, 60, 60));
        TAlabel.setText("0.00");
        jPanel3.add(TAlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 650, 109, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(60, 60, 60));
        jLabel14.setText("Total Allowance");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, 130, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(60, 60, 60));
        jLabel29.setText("Total Deduction");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 670, 130, -1));

        TDlabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        TDlabel.setForeground(new java.awt.Color(60, 60, 60));
        TDlabel.setText("0.00");
        jPanel3.add(TDlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 670, 109, -1));

        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 730, 60, 20));

        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 690, 60, 20));

        jSeparator20.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 720, 60, 20));

        jPanel1.setBackground(new java.awt.Color(195, 195, 195));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(40, 42, 43));
        jLabel23.setText("Date Hire");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(40, 42, 43));
        jLabel25.setText("Department");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, -1));

        idlabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        idlabel.setForeground(new java.awt.Color(40, 42, 43));
        idlabel.setText("Employee ID");
        jPanel1.add(idlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(40, 42, 43));
        jLabel26.setText("Designation");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, -1));

        lastname.setBackground(new java.awt.Color(195, 195, 195));
        lastname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastname.setText("Sandakalum");
        lastname.setBorder(null);
        lastname.setOpaque(false);
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(40, 42, 43));
        jLabel27.setText("Basic Salary");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(40, 42, 43));
        jLabel22.setText("First Name");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(40, 42, 43));
        jLabel28.setText("National ID");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(40, 42, 43));
        jLabel46.setText("Last Name");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        firstname.setBackground(new java.awt.Color(195, 195, 195));
        firstname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstname.setText("Maleesha");
        firstname.setBorder(null);
        firstname.setOpaque(false);
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 10));

        designation.setBackground(new java.awt.Color(195, 195, 195));
        designation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        designation.setBorder(null);
        designation.setOpaque(false);
        jPanel1.add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 200, 10));

        department.setBackground(new java.awt.Color(195, 195, 195));
        department.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        department.setBorder(null);
        department.setOpaque(false);
        jPanel1.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, 10));

        basicsalary.setBackground(new java.awt.Color(195, 195, 195));
        basicsalary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        basicsalary.setBorder(null);
        basicsalary.setOpaque(false);
        jPanel1.add(basicsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 200, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 200, 10));

        datehired.setBackground(new java.awt.Color(195, 195, 195));
        datehired.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        datehired.setBorder(null);
        datehired.setOpaque(false);
        jPanel1.add(datehired, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 200, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 10));

        nationalid.setBackground(new java.awt.Color(195, 195, 195));
        nationalid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nationalid.setBorder(null);
        nationalid.setOpaque(false);
        jPanel1.add(nationalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 10));

        EMPIDtxt.setBackground(new java.awt.Color(195, 195, 195));
        EMPIDtxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EMPIDtxt.setText("E2");
        EMPIDtxt.setBorder(null);
        EMPIDtxt.setOpaque(false);
        jPanel1.add(EMPIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 10));

        image.setBackground(new java.awt.Color(255, 255, 255));
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 160, 140));

        saveBtn.setBackground(new java.awt.Color(69, 70, 71));
        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setToolTipText("Save");
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 140, 30));

        calculateBtn.setBackground(new java.awt.Color(69, 70, 71));
        calculateBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calculateBtn.setForeground(new java.awt.Color(255, 255, 255));
        calculateBtn.setText("Calculate");
        calculateBtn.setToolTipText("Calculate");
        calculateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calculateBtnMouseEntered(evt);
            }
        });
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(calculateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 140, 30));

        pictureBrowse1.setBackground(new java.awt.Color(69, 70, 71));
        pictureBrowse1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pictureBrowse1.setForeground(new java.awt.Color(255, 255, 255));
        pictureBrowse1.setText("Clear");
        pictureBrowse1.setToolTipText("Clear");
        pictureBrowse1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pictureBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pictureBrowse1ActionPerformed(evt);
            }
        });
        jPanel1.add(pictureBrowse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 140, 30));

        image1.setBackground(new java.awt.Color(255, 255, 255));
        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_show_property_35px_1.png"))); // NOI18N
        image1.setToolTipText("Show Table");
        image1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        image1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image1MouseClicked(evt);
            }
        });
        jPanel1.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 40, 40));

        jLabel3.setForeground(new java.awt.Color(51, 52, 54));
        jLabel3.setText("Show Table");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 510, 380));

        lecturepanel.setBackground(new java.awt.Color(250, 250, 250));
        lecturepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setBackground(new java.awt.Color(250, 250, 250));
        jTabbedPane3.setForeground(new java.awt.Color(60, 62, 63));
        jTabbedPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane3.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jTabbedPane3.setOpaque(true);

        jPanel10.setBackground(new java.awt.Color(252, 212, 252));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectcomboLE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        selectcomboLE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Annual Bonus", "Bonus Earned", "Festival Allowance", "Meal/Tea Allowance", "Medical Reimbursement", "Night Allowance", "Three Months Loan", "Ten Months Loan", "Travelling Advance", " " }));
        jPanel10.add(selectcomboLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 150, -1));

        earningL.setBackground(new java.awt.Color(252, 212, 252));
        earningL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        earningL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        earningL.setBorder(null);
        earningL.setOpaque(false);
        jPanel10.add(earningL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 110, 30));
        jPanel10.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 110, 10));

        jLabel52.setBackground(new java.awt.Color(204, 204, 255));
        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(40, 42, 43));
        jLabel52.setText("Earnings :");
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        textareaLE.setColumns(20);
        textareaLE.setRows(5);
        jScrollPane3.setViewportView(textareaLE);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 260, 80));

        jLabel53.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(75, 75, 75));
        jLabel53.setText("Total Earnings :");
        jPanel10.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        totalEarningL.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        totalEarningL.setForeground(new java.awt.Color(75, 75, 75));
        totalEarningL.setText("0.00");
        jPanel10.add(totalEarningL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 80, -1));

        leclbl.setBackground(new java.awt.Color(252, 212, 252));
        leclbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        leclbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        leclbl.setText("Lectures");
        leclbl.setBorder(null);
        jPanel10.add(leclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        addLE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        addLE.setText("ADD");
        addLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLEActionPerformed(evt);
            }
        });
        jPanel10.add(addLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jTabbedPane3.addTab("EARNINGS", jPanel10);

        jPanel11.setBackground(new java.awt.Color(172, 248, 185));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setBackground(new java.awt.Color(204, 204, 255));
        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(40, 42, 43));
        jLabel39.setText("Deductions :");
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        deductionL.setBackground(new java.awt.Color(172, 248, 185));
        deductionL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deductionL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deductionL.setBorder(null);
        deductionL.setOpaque(false);
        jPanel11.add(deductionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 30));
        jPanel11.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, 10));

        textareaLD.setColumns(20);
        textareaLD.setRows(5);
        jScrollPane4.setViewportView(textareaLD);

        jPanel11.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, 100));

        jLabel40.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(75, 75, 75));
        jLabel40.setText("Total Deduction :");
        jPanel11.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        totalDeductionL.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        totalDeductionL.setForeground(new java.awt.Color(75, 75, 75));
        totalDeductionL.setText("0.00");
        jPanel11.add(totalDeductionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 109, -1));

        selectcomboLD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        selectcomboLD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Festival Advance", "No Pay", "Multipurpose Loan", "Personal Acci. Insuarance", "Three Months Loan", "Ten Months Loan", "Welfare Association", "AGRAHARA" }));
        jPanel11.add(selectcomboLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 150, -1));

        addLD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        addLD.setText("ADD");
        addLD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLDActionPerformed(evt);
            }
        });
        jPanel11.add(addLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        leclbl2.setBackground(new java.awt.Color(172, 248, 185));
        leclbl2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        leclbl2.setText("Lectures");
        leclbl2.setBorder(null);
        jPanel11.add(leclbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        jTabbedPane3.addTab("DEDUCTIONS", jPanel11);

        lecturepanel.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 530, 290));

        jPanel3.add(lecturepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 1110, 330));

        staffpanel.setBackground(new java.awt.Color(250, 250, 250));
        staffpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(250, 250, 250));
        jTabbedPane2.setForeground(new java.awt.Color(60, 62, 63));
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane2.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jTabbedPane2.setOpaque(true);

        jPanel8.setBackground(new java.awt.Color(252, 212, 252));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(40, 42, 43));
        jLabel17.setText("Overtime(hour) ");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel30.setBackground(new java.awt.Color(204, 204, 255));
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(40, 42, 43));
        jLabel30.setText("Earnings :");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(40, 42, 43));
        jLabel34.setText("Rate Per Hour ");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(40, 42, 43));
        jLabel35.setText("Total Over Time ");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel36.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(75, 75, 75));
        jLabel36.setText("Total Earnings :");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        totalEarningS.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        totalEarningS.setForeground(new java.awt.Color(75, 75, 75));
        totalEarningS.setText("0.00");
        jPanel8.add(totalEarningS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 80, -1));

        earningS.setBackground(new java.awt.Color(252, 212, 252));
        earningS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        earningS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        earningS.setBorder(null);
        earningS.setOpaque(false);
        jPanel8.add(earningS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 110, 30));
        jPanel8.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 110, 10));
        jPanel8.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 90, 10));

        totEarningS.setBackground(new java.awt.Color(252, 212, 252));
        totEarningS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totEarningS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totEarningS.setText("00.00");
        totEarningS.setBorder(null);
        jPanel8.add(totEarningS, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 90, 30));
        jPanel8.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, 10));

        otEarningS.setBackground(new java.awt.Color(252, 212, 252));
        otEarningS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        otEarningS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        otEarningS.setBorder(null);
        otEarningS.setOpaque(false);
        otEarningS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                otEarningSKeyReleased(evt);
            }
        });
        jPanel8.add(otEarningS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, 30));

        rphEarningS.setBackground(new java.awt.Color(252, 212, 252));
        rphEarningS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rphEarningS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rphEarningS.setBorder(null);
        rphEarningS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rphEarningSKeyReleased(evt);
            }
        });
        jPanel8.add(rphEarningS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 90, 30));
        jPanel8.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 90, 10));

        staffLbl.setBackground(new java.awt.Color(252, 212, 252));
        staffLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        staffLbl.setText("Staff");
        staffLbl.setBorder(null);
        jPanel8.add(staffLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        textareaSE.setColumns(20);
        textareaSE.setRows(5);
        jScrollPane1.setViewportView(textareaSE);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 260, 80));

        selectcomboSE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        selectcomboSE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Annual Bonus", "Bonus Earned", "Festival Allowance", "Meal/Tea Allowance", "Medical Reimbursement", "Night Allowance", "Three Months Loan", "Ten Months Loan", "Travelling Advance", " " }));
        jPanel8.add(selectcomboSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 150, -1));

        addSE.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        addSE.setText("ADD");
        addSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSEActionPerformed(evt);
            }
        });
        jPanel8.add(addSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jTabbedPane2.addTab("EARNINGS", jPanel8);

        jPanel9.setBackground(new java.awt.Color(172, 248, 185));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(75, 75, 75));
        jLabel38.setText("Total Deduction :");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        totalDeductionS.setFont(new java.awt.Font("Arial Unicode MS", 1, 15)); // NOI18N
        totalDeductionS.setForeground(new java.awt.Color(75, 75, 75));
        totalDeductionS.setText("0.00");
        jPanel9.add(totalDeductionS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 109, -1));

        jLabel32.setBackground(new java.awt.Color(204, 204, 255));
        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(40, 42, 43));
        jLabel32.setText("Deductions :");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        deductionS.setBackground(new java.awt.Color(172, 248, 185));
        deductionS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deductionS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deductionS.setBorder(null);
        deductionS.setOpaque(false);
        jPanel9.add(deductionS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 30));
        jPanel9.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, 10));

        selectcomboSD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        selectcomboSD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Festival Advance", "No Pay", "Multipurpose Loan", "Personal Acci. Insuarance", "Three Months Loan", "Ten Months Loan", "Welfare Association", "AGRAHARA" }));
        jPanel9.add(selectcomboSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 150, -1));

        addSD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        addSD.setText("ADD");
        addSD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSDActionPerformed(evt);
            }
        });
        jPanel9.add(addSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        textareaSD.setColumns(20);
        textareaSD.setRows(5);
        jScrollPane2.setViewportView(textareaSD);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, 100));

        staffLabl2.setBackground(new java.awt.Color(172, 248, 185));
        staffLabl2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        staffLabl2.setText("Staff");
        staffLabl2.setBorder(null);
        jPanel9.add(staffLabl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        jTabbedPane2.addTab("DEDUCTIONS", jPanel9);

        staffpanel.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 530, 290));

        jPanel3.add(staffpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 690, 330));

        jPanel4.setBackground(new java.awt.Color(195, 195, 195));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Permenet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel4.setToolTipText("");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setBackground(new java.awt.Color(204, 204, 255));
        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(40, 42, 43));
        jLabel33.setText("EPF(10%) :");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel4.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 70, 10));

        sEPF.setBackground(new java.awt.Color(195, 195, 195));
        sEPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sEPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sEPF.setText("00.00");
        sEPF.setBorder(null);
        sEPF.setOpaque(false);
        jPanel4.add(sEPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 70, 30));
        jPanel4.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 70, 10));

        sETF.setBackground(new java.awt.Color(195, 195, 195));
        sETF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sETF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sETF.setText("00.00");
        sETF.setBorder(null);
        sETF.setOpaque(false);
        jPanel4.add(sETF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 70, 30));

        jLabel49.setBackground(new java.awt.Color(204, 204, 255));
        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(40, 42, 43));
        jLabel49.setText("ETF(3%) :");
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 530, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel6.setToolTipText(" Back");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, -1, 40));

        salaryCalcul.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 740));

        getContentPane().add(salaryCalcul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*public void monthchooser() {

        switch (monthlb.getSelectedIndex()) {
            case 0: {
                startdate = yearlb.getText() + "-01-01";
                enddate = yearlb.getText() + "-02-01";
                break;
            }
            case 1: {
                startdate = yearlb.getText() + "-02-01";
                enddate = yearlb.getText() + "-03-01";
                break;
            }
            case 2: {
                startdate = yearlb.getText() + "-03-01";
                enddate = yearlb.getText() + "-04-01";
                break;
            }
            case 3: {
                startdate = yearlb.getText() + "-04-01";
                enddate = yearlb.getText() + "-05-01";
                break;
            }
            case 4: {
                startdate = yearlb.getText() + "-05-01";
                enddate = yearlb.getText() + "-06-01";
                break;
            }
            case 5: {
                startdate = yearlb.getText() + "-06-01";
                enddate = yearlb.getText() + "-07-01";
                break;
            }
            case 6: {
                startdate = yearlb.getText() + "-07-01";
                enddate = yearlb.getText() + "-08-01";
                break;
            }
            case 7: {
                startdate = yearlb.getText() + "-08-01";
                enddate = yearlb.getText() + "-09-01";
                break;
            }
            case 8: {
                startdate = yearlb.getText() + "-09-01";
                enddate = yearlb.getText() + "-10-01";
                break;
            }
            case 9: {
                startdate = yearlb.getText() + "-10-01";
                enddate = yearlb.getText() + "-11-01";
                break;
            }
            case 10: {
                startdate = yearlb.getText() + "-11-01";
                enddate = yearlb.getText() + "-12-01";
                break;
            }
            case 11: {
                startdate = yearlb.getText() + "-12-01";
                enddate = String.valueOf(Integer.parseInt(yearlb.getText()) + 1) + "-01-01";
                break;
            }
        }

    }*/

    private void lectlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectlblMouseClicked
        // TODO add your handling code here:
        lblSetColor(lectlbl);
        lblResetColor(stafflbl);
        lecturepanel.setVisible(true);
        staffpanel.setVisible(false);
        leclbl.setVisible(true);
        leclbl2.setVisible(true);
        var.setText("L");
        idlabel.setText("Lecturer ID");
        choice = false;

    }//GEN-LAST:event_lectlblMouseClicked

    private void lectlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectlblMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lectlblMouseEntered

    private void lectlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectlblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lectlblMouseExited

    private void stafflblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stafflblMouseClicked
        // TODO add your handling code here:
        lblSetColor(stafflbl);
        lblResetColor(lectlbl);
        srcBtn.setEnabled(true);
        srcBtn.setEnabled(true);
        staffpanel.setVisible(true);
        lecturepanel.setVisible(false);
        staffLbl.setVisible(true);
        staffLabl2.setVisible(true);
        var.setText("E");
        idlabel.setText("Staff ID");
        choice = true;

    }//GEN-LAST:event_stafflblMouseClicked

    private void stafflblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stafflblMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_stafflblMouseEntered

    private void stafflblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stafflblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_stafflblMouseExited

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

        sal = new Salary();

        sal.setId(Integer.parseInt(search.getText()));
        sal.setIssuedid(EMPIDtxt.getText());
        sal.setName(firstname.getText() + " " + lastname.getText());
        sal.setDesignation(designation.getText());
        int rng = (int) ((Math.random() * (21 - 15)) + 15);
        sal.setNoOFDays("20");
        sal.setPresentDays(String.valueOf(rng));
        sal.setLeaves(String.valueOf(20 - rng));
        sal.setDate(dateFormat.format(cal.getTime()));
        sal.setEarnings(TAlabel.getText());
        sal.setDeduction(TDlabel.getText());
        sal.setEPF(sEPF.getText());
        sal.setETF(sETF.getText());
        sal.setNopay("0");
        sal.setGrossSalary(String.valueOf(gross_salary));
        sal.setTotalDeduction(TDlabel.getText());
        sal.setNetSalary(Finallabel.getText());
        sal.setBankAcc("8009062821");

        int check = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?", "Add Record", JOptionPane.YES_NO_OPTION);

        if (check == 0) {
            //empSrv.salarySave(emp);
            salsrv.salarySave(sal);

        }

        PDFJpannel rj = new PDFJpannel();
        rj.setVisible(true);
        jre = new jReportEntity();

        jre.setEmpID(EMPIDtxt.getText());
        jrs.selectSlipDetailsService(jre);

        rj.empidtxt.setText(EMPIDtxt.getText());
        rj.nametxt.setText(firstname.getText() + " " + lastname.getText());
        rj.desigtxt.setText(designation.getText());
        rj.no_of_days.setText("20");
        rj.present_days.setText(sal.getPresentDays());
        rj.leaves.setText(sal.getLeaves());
        if (choice) {
            rj.earnings.setText(totEarningS.getText() + "0\t" + "Over Time\n" + textareaSE.getText());
            rj.deductions.setText(textareaSD.getText());
        } else {
            rj.earnings.setText(textareaLE.getText());
            rj.deductions.setText(textareaLD.getText());
        }

        rj.bankAcc.setText(sal.getBankAcc());
        rj.GROSSSALARY.setText(sal.getGrossSalary());
        rj.TOTD.setText(TDlabel.getText());
        rj.NETSAL.setText(sal.getNetSalary());
        rj.empEpf.setText(sal.getEPF());
        rj.jLabel30.setText(sEPF.getText());
        rj.jLabel8.setText(sETF.getText());

        
        clear();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void pictureBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pictureBrowse1ActionPerformed
        clear();
     }//GEN-LAST:event_pictureBrowse1ActionPerformed

    private void image1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image1MouseClicked
        // TODO add your handling code here:
        Salary_Info_Frame salobj = new Salary_Info_Frame();
        salobj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_image1MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        // TODO add your handling code here:
        this.dispose();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel48MouseClicked

    private void srcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcBtnActionPerformed
        emp = new Employee();
        emp.setId(Integer.parseInt(search.getText()));
        if (choice) {
            empSrv.search(emp, "staff");
        } else {
            empSrv.search(emp, "lecturer");
        }
        EMPIDtxt.setText(String.valueOf(emp.getIssuedid()));
        firstname.setText(emp.getFirstname());
        lastname.setText(emp.getLastname());
        nationalid.setText(emp.getNationlid());
        designation.setText(emp.getDesignation());
        department.setText(emp.getDepartment());
        datehired.setText(emp.getDatehired());
        basicsalary.setText(emp.getBasicsalary());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(emp.getImage()).getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH));
        image.setIcon(imageIcon);


    }//GEN-LAST:event_srcBtnActionPerformed

    private void addSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSEActionPerformed
        if (selectcomboSE.getSelectedItem().equals("Select")) {
            JOptionPane.showMessageDialog(null, "No Item Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (textareaSE.getText().equals("")) {
            textareaSE.setText(earningS.getText() + ".00" + "\t" + selectcomboSE.getSelectedItem());
        } else {
            textareaSE.setText(textareaSE.getText() + "\n" + earningS.getText() + ".00" + "\t" + selectcomboSE.getSelectedItem());
        }
        v = Double.parseDouble(totalEarningS.getText()) + Double.parseDouble(earningS.getText());
        totalEarningS.setText(String.valueOf(v));

    }//GEN-LAST:event_addSEActionPerformed

    private void addSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSDActionPerformed
        if (selectcomboSD.getSelectedItem().equals("Select")) {
            JOptionPane.showMessageDialog(null, "No Item Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (textareaSD.getText().equals("")) {
            textareaSD.setText(deductionS.getText() + ".00" + "\t" + selectcomboSD.getSelectedItem());
        } else {
            textareaSD.setText(textareaSD.getText() + "\n" + deductionS.getText() + ".00" + "\t" + selectcomboSD.getSelectedItem());
        }
        v = Double.parseDouble(totalDeductionS.getText()) + Double.parseDouble(deductionS.getText());
        totalDeductionS.setText(String.valueOf(v));
    }//GEN-LAST:event_addSDActionPerformed

    private void addLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLDActionPerformed
        if (selectcomboLD.getSelectedItem().equals("Select")) {
            JOptionPane.showMessageDialog(null, "No Item Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (textareaLD.getText().equals("")) {
            textareaLD.setText(deductionL.getText() + "\t" + selectcomboLD.getSelectedItem());
        } else {
            textareaLD.setText(textareaLD.getText() + "\n" + deductionL.getText() + "\t" + selectcomboLD.getSelectedItem());
        }
        v = Double.parseDouble(totalDeductionL.getText()) + Double.parseDouble(deductionL.getText());
        totalDeductionL.setText(String.valueOf(v));
    }//GEN-LAST:event_addLDActionPerformed

    private void calculateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateBtnMouseClicked
        bsal = Integer.valueOf(basicsalary.getText());
        sEPF.setText(String.valueOf(0.1 * bsal));
        sETF.setText(String.valueOf(0.03 * bsal));
        double TA, TD, Final;
        if (choice) {
            //Integer.valueOf()
            TA = Double.parseDouble(totEarningS.getText()) + Double.parseDouble(totalEarningS.getText()) + bsal;
            TAlabel.setText(String.valueOf(TA));

            TD = Double.parseDouble(totalDeductionS.getText()) + Double.parseDouble(sEPF.getText());
            TDlabel.setText(String.valueOf(TD));

            Final = TA - TD;
            Finallabel.setText(String.valueOf(Final));

            gross_salary = TA;
        } else {
            TA = Double.parseDouble(totalEarningL.getText()) + bsal;
            TAlabel.setText(String.valueOf(TA));

            TD = Double.parseDouble(totalDeductionL.getText()) + Double.parseDouble(sEPF.getText());
            TDlabel.setText(String.valueOf(TD));

            Final = TA - TD;
            Finallabel.setText(String.valueOf(Final));

            gross_salary = TA;
        }

        if (!Finallabel.getText().equals("0.00")) {
            saveBtn.setEnabled(true);
        }
    }//GEN-LAST:event_calculateBtnMouseClicked

    private void addLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLEActionPerformed
        if (selectcomboLE.getSelectedItem().equals("Select")) {
            JOptionPane.showMessageDialog(null, "No Item Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (textareaLE.getText().equals("")) {
            textareaLE.setText(earningL.getText() + "\t" + selectcomboLE.getSelectedItem());
        } else {
            textareaLE.setText(textareaLE.getText() + "\n" + earningL.getText() + "\t" + selectcomboLE.getSelectedItem());
        }
        v = Double.parseDouble(totalEarningL.getText()) + Double.parseDouble(earningL.getText());
        totalEarningL.setText(String.valueOf(v));
    }//GEN-LAST:event_addLEActionPerformed

    private void otEarningSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otEarningSKeyReleased
        double var1;
        if (!rphEarningS.getText().equals("")) {
            var1 = Integer.valueOf(otEarningS.getText()) * Integer.valueOf(rphEarningS.getText());
            totEarningS.setText(String.valueOf(var1));
        }
    }//GEN-LAST:event_otEarningSKeyReleased

    private void rphEarningSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rphEarningSKeyReleased
        double var1;
        if (!otEarningS.getText().equals("")) {
            var1 = Integer.valueOf(otEarningS.getText()) * Integer.valueOf(rphEarningS.getText());
            totEarningS.setText(String.valueOf(var1));
        }
    }//GEN-LAST:event_rphEarningSKeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        PayrollMain var = new PayrollMain();
        var.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        PayrollMain var = new PayrollMain();
        var.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void calculateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_calculateBtnMouseEntered

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculateBtnActionPerformed

    public void lblSetColor(JLabel lable) {

        lable.setBackground(new java.awt.Color(73, 74, 75));

    }

    public void lblResetColor(JLabel lable) {

        lable.setBackground(new java.awt.Color(51, 52, 54));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salaryCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salaryCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salaryCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salaryCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salaryCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EMPIDtxt;
    private javax.swing.JLabel Finallabel;
    private javax.swing.JLabel TAlabel;
    private javax.swing.JLabel TDlabel;
    private javax.swing.JButton addLD;
    private javax.swing.JButton addLE;
    private javax.swing.JButton addSD;
    private javax.swing.JButton addSE;
    private javax.swing.JTextField basicsalary;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JTextField datehired;
    private javax.swing.JTextField deductionL;
    private javax.swing.JTextField deductionS;
    private javax.swing.JTextField department;
    private javax.swing.JTextField designation;
    private javax.swing.JTextField earningL;
    private javax.swing.JTextField earningS;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField leclbl;
    private javax.swing.JTextField leclbl2;
    private javax.swing.JLabel lectlbl;
    private javax.swing.JPanel lecturepanel;
    private javax.swing.JTextField nationalid;
    private javax.swing.JTextField otEarningS;
    private javax.swing.JButton pictureBrowse1;
    private javax.swing.JTextField rphEarningS;
    private javax.swing.JTextField sEPF;
    private javax.swing.JTextField sETF;
    private javax.swing.JPanel salaryCalcul;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox<String> selectcomboLD;
    private javax.swing.JComboBox<String> selectcomboLE;
    private javax.swing.JComboBox<String> selectcomboSD;
    private javax.swing.JComboBox<String> selectcomboSE;
    private javax.swing.JButton srcBtn;
    private javax.swing.JTextField staffLabl2;
    private javax.swing.JTextField staffLbl;
    private javax.swing.JLabel stafflbl;
    private javax.swing.JPanel staffpanel;
    private javax.swing.JTextArea textareaLD;
    private javax.swing.JTextArea textareaLE;
    private javax.swing.JTextArea textareaSD;
    private javax.swing.JTextArea textareaSE;
    private javax.swing.JTextField totEarningS;
    private javax.swing.JLabel totalDeductionL;
    private javax.swing.JLabel totalDeductionS;
    private javax.swing.JLabel totalEarningL;
    private javax.swing.JLabel totalEarningS;
    private javax.swing.JButton var;
    // End of variables declaration//GEN-END:variables
}
