/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_;

import javax.swing.JPanel;


/**
 *
 * @author Shehan Tharaka
 */
public class studentPaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form studentPaymentForm
     */
    public studentPaymentForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        c = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        d = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        coursePaymentDetailsLable1 = new javax.swing.JLabel();
        coursePaymentDetailsLable = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addNewCoursePaymentLable1 = new javax.swing.JLabel();
        addNewCoursePaymentLable = new javax.swing.JLabel();
        a = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        freeStructureLable = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addCoursetPaymentLable1 = new javax.swing.JLabel();
        addCoursetPaymentLable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b.setBackground(new java.awt.Color(255, 204, 255));
        b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMouseExited(evt);
            }
        });
        b.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_mastercard_logo_125px.png"))); // NOI18N
        jLabel9.setToolTipText("Course Payment");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        b.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 130));

        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 200, 170));

        c.setBackground(new java.awt.Color(255, 204, 255));
        c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cMouseExited(evt);
            }
        });
        c.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cash_in_hand_125px.png"))); // NOI18N
        jLabel10.setToolTipText("Course Payment");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        c.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 150));

        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 200, 170));

        d.setBackground(new java.awt.Color(255, 204, 255));
        d.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dMouseExited(evt);
            }
        });
        d.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_edit_property_125px.png"))); // NOI18N
        jLabel11.setToolTipText("Payment Details");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        d.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 130));

        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 200, 170));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coursePaymentDetailsLable1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        coursePaymentDetailsLable1.setForeground(new java.awt.Color(51, 51, 55));
        coursePaymentDetailsLable1.setText("Course ");
        coursePaymentDetailsLable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coursePaymentDetailsLable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursePaymentDetailsLable1MouseClicked(evt);
            }
        });
        jPanel6.add(coursePaymentDetailsLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, -1));

        coursePaymentDetailsLable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        coursePaymentDetailsLable.setForeground(new java.awt.Color(51, 51, 55));
        coursePaymentDetailsLable.setText("Payment Details");
        coursePaymentDetailsLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coursePaymentDetailsLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursePaymentDetailsLableMouseClicked(evt);
            }
        });
        jPanel6.add(coursePaymentDetailsLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 200, 60));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addNewCoursePaymentLable1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addNewCoursePaymentLable1.setForeground(new java.awt.Color(51, 51, 55));
        addNewCoursePaymentLable1.setText("Add Student");
        addNewCoursePaymentLable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNewCoursePaymentLable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewCoursePaymentLable1MouseClicked(evt);
            }
        });
        jPanel5.add(addNewCoursePaymentLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        addNewCoursePaymentLable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addNewCoursePaymentLable.setForeground(new java.awt.Color(51, 51, 55));
        addNewCoursePaymentLable.setText("Registation Payment");
        addNewCoursePaymentLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNewCoursePaymentLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewCoursePaymentLableMouseClicked(evt);
            }
        });
        jPanel5.add(addNewCoursePaymentLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 200, 60));

        a.setBackground(new java.awt.Color(255, 204, 255));
        a.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aMouseExited(evt);
            }
        });
        a.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_broadcasting_125px.png"))); // NOI18N
        jLabel12.setToolTipText("Fee Structure");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        a.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, -1));

        jLabel13.setToolTipText("Fee Structure");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        a.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 120));

        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 170));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel15.setToolTipText(" Back");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 50, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        freeStructureLable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        freeStructureLable.setForeground(new java.awt.Color(51, 51, 55));
        freeStructureLable.setText("Fee Structure");
        freeStructureLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        freeStructureLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                freeStructureLableMouseClicked(evt);
            }
        });
        jPanel3.add(freeStructureLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 60));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCoursetPaymentLable1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addCoursetPaymentLable1.setForeground(new java.awt.Color(51, 51, 55));
        addCoursetPaymentLable1.setText("Add ");
        addCoursetPaymentLable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCoursetPaymentLable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCoursetPaymentLable1MouseClicked(evt);
            }
        });
        jPanel4.add(addCoursetPaymentLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, -1));

        addCoursetPaymentLable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addCoursetPaymentLable.setForeground(new java.awt.Color(51, 51, 55));
        addCoursetPaymentLable.setText("Course Payment");
        addCoursetPaymentLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCoursetPaymentLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCoursetPaymentLableMouseClicked(evt);
            }
        });
        jPanel4.add(addCoursetPaymentLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 200, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1120, 430));

        jPanel2.setBackground(new java.awt.Color(51, 52, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("X");
        jLabel32.setToolTipText("close");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 30, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-");
        jLabel22.setToolTipText("minimize");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 30, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 230, 230));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_online_payment_75px.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setText("Student.Pay.Mgt System");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 170, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 230, 230));
        jLabel8.setText("Stu.Payment.Form");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 340, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void freeStructureLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeStructureLableMouseClicked
      
    }//GEN-LAST:event_freeStructureLableMouseClicked

    private void addCoursetPaymentLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCoursetPaymentLableMouseClicked
       
    }//GEN-LAST:event_addCoursetPaymentLableMouseClicked

    private void coursePaymentDetailsLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursePaymentDetailsLableMouseClicked
    }//GEN-LAST:event_coursePaymentDetailsLableMouseClicked

    private void addNewCoursePaymentLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewCoursePaymentLableMouseClicked
        
    }//GEN-LAST:event_addNewCoursePaymentLableMouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(studentPaymentForm.ICONIFIED);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void addNewCoursePaymentLable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewCoursePaymentLable1MouseClicked
    }//GEN-LAST:event_addNewCoursePaymentLable1MouseClicked

    private void addCoursetPaymentLable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCoursetPaymentLable1MouseClicked
    }//GEN-LAST:event_addCoursetPaymentLable1MouseClicked

    private void coursePaymentDetailsLable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursePaymentDetailsLable1MouseClicked
    }//GEN-LAST:event_coursePaymentDetailsLable1MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        setColor(b);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        resetColor(b);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        setColor(c);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        resetColor(c);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        setColor(d);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        resetColor(d);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        setColor(a);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        resetColor(a);
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
    }//GEN-LAST:event_jLabel12MousePressed

    private void aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseEntered
        setColor(a);
    }//GEN-LAST:event_aMouseEntered

    private void aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseExited
        resetColor(a);
    }//GEN-LAST:event_aMouseExited

    private void bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseEntered
        setColor(b);
    }//GEN-LAST:event_bMouseEntered

    private void bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseExited
        resetColor(b);
    }//GEN-LAST:event_bMouseExited

    private void cMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseEntered
        setColor(c);
    }//GEN-LAST:event_cMouseEntered

    private void cMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseExited
        resetColor(c);
    }//GEN-LAST:event_cMouseExited

    private void dMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseEntered
        setColor(d);
    }//GEN-LAST:event_dMouseEntered

    private void dMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseExited
        resetColor(d);
    }//GEN-LAST:event_dMouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        studentForm strf = new studentForm();
        strf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        setColor(a);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        resetColor(a);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        freeStructureForm now = new freeStructureForm();
        now.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        addStudentRegistrationPaymentForm now = new addStudentRegistrationPaymentForm();
        now.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        addCoursePaymentForm now = new addCoursePaymentForm();
        now.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        coursePaymentDetailsForm now = new coursePaymentDetailsForm();
        now.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
        freeStructureForm now = new freeStructureForm();
        now.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_aMouseClicked

    private void bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseClicked
        addStudentRegistrationPaymentForm now = new addStudentRegistrationPaymentForm();
        now.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
        addCoursePaymentForm now = new addCoursePaymentForm();
        now.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cMouseClicked

    private void dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseClicked
        coursePaymentDetailsForm now = new coursePaymentDetailsForm();
        now.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dMouseClicked

    public void setColor(JPanel panel){
    
        panel.setBackground(new java.awt.Color(159, 90, 253));
    }
    
    public void resetColor(JPanel panel){
    
        panel.setBackground(new java.awt.Color(255,204,255));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentPaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a;
    private javax.swing.JLabel addCoursetPaymentLable;
    private javax.swing.JLabel addCoursetPaymentLable1;
    private javax.swing.JLabel addNewCoursePaymentLable;
    private javax.swing.JLabel addNewCoursePaymentLable1;
    private javax.swing.JPanel b;
    private javax.swing.JPanel c;
    private javax.swing.JLabel coursePaymentDetailsLable;
    private javax.swing.JLabel coursePaymentDetailsLable1;
    private javax.swing.JPanel d;
    private javax.swing.JLabel freeStructureLable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
