/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_;

import Entity_.Student;
import java.awt.Color;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.AbstractTableModel;
import Service_.StudentService;

/**
 *
 * @author MY_PC
 */
public class studentsDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form addNewCoursePaymentForm
     */
    
    private StudentService sc=new StudentService();
    
    
    public studentsDetailsForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        tableLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        studentId = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 52, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("X");
        jLabel32.setToolTipText("close");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 30, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-");
        jLabel22.setToolTipText("minimize");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 30, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 230, 230));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_student_male_88px_2.png"))); // NOI18N
        jLabel6.setText("NSBM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setText("Student.Pay.Mgt System");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 170, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 230, 230));
        jLabel8.setText("Stu.Details");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_30px.png"))); // NOI18N
        jLabel1.setToolTipText("Search");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 50, 40));

        search.setBackground(new java.awt.Color(51, 52, 54));
        search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(240, 240, 240));
        search.setBorder(null);
        search.setOpaque(false);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 280, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 280, 20));

        studentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studentId.setForeground(new java.awt.Color(240, 240, 240));
        studentId.setText("Student ID");
        jPanel1.add(studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 260));

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addB.setText("ADD");
        jPanel3.add(addB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 580, -1, -1));

        studentTable.setForeground(new java.awt.Color(102, 0, 255));
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1080, 330));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel15.setToolTipText(" Back");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 50, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1120, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(studentsDetailsForm.ICONIFIED);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        studentRegistrationForm nf = new studentRegistrationForm();
        nf.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_jLabel15MouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        search();
    }//GEN-LAST:event_searchKeyReleased

    
    /**
     * search student details
     */
    public void search(){
        
        String value=search.getText();

            List<Student> student=sc.search(value);

            String[] colName={"ID","Student Name","Age","NIC","Gender","Telephone","Email","Address","Trustee_Name","Branch","Academic Year","Picture"};
            Object[][] rows=new Object[student.size()][15];

                for(int i=0;i<student.size();i++)
                {
                    rows[i][0]=student.get(i).getSid();
                    rows[i][1]=student.get(i).getsName();
                    rows[i][2]=student.get(i).getAge();
                    rows[i][3]=student.get(i).getNic();
                    rows[i][4]=student.get(i).getGender();
                    rows[i][5]=student.get(i).getTelephone();
                    rows[i][6]=student.get(i).getEmail();
                    ImageIcon img=new ImageIcon(new ImageIcon(student.get(i).getPicture()).getImage().getScaledInstance(70,70,Image.SCALE_SMOOTH));
                    rows[i][11]=img;
                    rows[i][7]=student.get(i).getAddress();
                    rows[i][8]=student.get(i).getTName();
                    rows[i][9]=student.get(i).getBranch();
                    rows[i][10]=student.get(i).getaYear();
                }
            myModel mmd=new myModel(rows,colName);
            studentTable.setModel(mmd);
            studentTable.setRowHeight(70);
            studentTable.getColumnModel().getColumn(7).setPreferredWidth(70);
            studentTable.setShowGrid(true);
            studentTable.setGridColor(Color.black);
            studentTable.setSelectionBackground(Color.lightGray);
    }
    
    
    /**
     * get students details
     */
    public void tableLoad(){
        
        List<Student> student=sc.getAll();

        String[] colName={"ID","Student Name","Age","NIC","Gender","Telephone","Email","Address","Trustee_Name","Branch","Academic Year","Picture"};
        Object[][] rows=new Object[student.size()][15];

            for(int i=0;i<student.size();i++)
            {
                rows[i][0]=student.get(i).getSid();
                rows[i][1]=student.get(i).getsName();
                rows[i][2]=student.get(i).getAge();
                rows[i][3]=student.get(i).getNic();
                rows[i][4]=student.get(i).getGender();
                rows[i][5]=student.get(i).getTelephone();
                rows[i][6]=student.get(i).getEmail();
                ImageIcon img=new ImageIcon(new ImageIcon(student.get(i).getPicture()).getImage().getScaledInstance(70,70,Image.SCALE_SMOOTH));
                rows[i][11]=img;
                rows[i][7]=student.get(i).getAddress();
                rows[i][8]=student.get(i).getTName();
                rows[i][9]=student.get(i).getBranch();
                rows[i][10]=student.get(i).getaYear();
            }
        myModel mmd=new myModel(rows,colName);
        studentTable.setModel(mmd);
        studentTable.setRowHeight(70);
        studentTable.getColumnModel().getColumn(7).setPreferredWidth(70);
        studentTable.setShowGrid(true);
        studentTable.setGridColor(Color.black);
        studentTable.setSelectionBackground(Color.lightGray);
    }
    
    
    public class myModel extends AbstractTableModel{

        private String[] colums;
        private Object[][] rows;

        public myModel(){}

        public myModel(Object[][] data,String[] columnsName)          
        {
            this.colums=columnsName;
            this.rows=data;
        }

        public Class getColumnClass(int col)
        {
        //the index of the image column is 14
            if(col==12)
            {
                return Icon.class;
            }
            else
            {
                return getValueAt(0,col).getClass();
            }
        }

        @Override
        public int getRowCount() {
            return this.rows.length;
        }


        @Override
        public int getColumnCount() {
            return this.colums.length; 
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            return this.rows[rowIndex][columnIndex];  
        }

        @Override
        public String getColumnName(int col)
        {
            return this.colums[col];
        }
    
}
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentsDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentsDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentsDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentsDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentsDetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField search;
    private javax.swing.JLabel studentId;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
